name: Publish Docker Image and Deploy

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set Environment vars
        run: sed -i "s|%DBCONSTRING%|${{ secrets.INT_DB }}|g" FourMinator/appsettings.secret.json
        


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fterdev/4minator

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_int:
    needs: [push_to_registry]
    name: Deploy to IFS01
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IFS01_KEY }} 
      
      - name: Execute Deploy Script on Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no deployer@${{ secrets.IFS01_IP }} 'bash /home/deployer/deploy-server.sh'
          
      
    
   
      

